#!/bin/sh

rsync -av -e'ssh -p 68' --delete --exclude /feed/ --exclude /.certificates/ --exclude /.git/ --exclude /.gitignore ~/gemini/ root@spool-five.com:/home/gemini/gemini/content/
rsync -av -e'ssh -p 68' --delete ~/spoolfive/ root@spool-five.com:/var/www/spoolfive
